inherit_gem:
  rubocop-govuk:
    - "config/default.yml"
    - "config/rails.yml"

inherit_mode:
  merge:
    - Exclude

# This is not supported for Mongoid
Rails/FindEach:
  Enabled: false

# This is not supported for Mongoid
Rails/DynamicFindBy:
  Whitelist:
    - find_by_slug
