development:
  host: localhost
  database: govuk_content_development
  persist_in_safe_mode: true
  autocreate_indexes: true

test:
  host: localhost
  # Don't want this interfering with a concurrent Panopticon test run
  database: govuk_content_publisher_test
  autocreate_indexes: true

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
