development:
  clients:
    default:
      uri: mongodb://localhost/govuk_content_development

test:
  clients:
    default:
      uri: mongodb://localhost/govuk_travel_advice_publisher_test

# set these environment variables on your prod server
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
