development:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] || "mongodb://localhost/travel_advice_publisher_development" %>

test:
  clients:
    default:
      uri: <%= ENV["TEST_MONGODB_URI"] || "mongodb://localhost/travel_advice_publisher_test" %>

# set these environment variables on your prod server
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
